# https://doc.rust-lang.org/stable/clippy/index.html

doc-valid-idents = [
  "JetStream",
  "MongoDB",
  "NATS",
  "OpenTelemetry",
  "WebAssembly",
  "WebSocket",
]

allowed-duplicate-crates = [
  "core-foundation",
  "jni-sys",
  "cpufeatures",
  "embedded-io",
  "foldhash",
  "getrandom",
  "hashbrown",
  "linux-raw-sys",
  "rand",
  "rand_chacha",
  "rand_core",
  "r-efi",
  "reqwest",
  "rustix",
  "rustls",
  "rustls-webpki",
  "thiserror",
  "thiserror-impl",
  "tokio-rustls",
  "wasm-encoder",
  "wasm-metadata",
  "wasmparser",
  "webpki-roots",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
  "wit-bindgen",
  "wit-bindgen-core",
  "wit-bindgen-rust",
  "wit-bindgen-rust-macro",
  "wit-component",
  "wit-parser",
]
